config/routes.rb
Rails.application.routes.draw do
  get 'blogs/index'
  devise_for :users

  root to:'homes#top'
  
  #destroy_user_session DELETE /users/sign_out(.:format) devise/sessions#destroy
  delete  "users/sign_out" => "devise/sessions#destroy"
  
  get "/home/about" => "homes#about"
  resources:books
  resources:users,only: [:index, :create, :edit, :show, :update, :destroy]
  resources :blogs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to:user

  validates :title, presence: true
  validates :body, presence: true,length: { maximum: 200}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
 has_many :books,dependent: :destroy
 has_one_attached :profile_image

def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  validates :name, uniqueness: true,length: { minimum: 2, maximum: 20}
  validates :introduction, length: { maximum: 50 }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys: [:email,
                                                      :name])
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
    @blog = Blog.new
  end
  
  def new
    @blog = Blog.new
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def create
    Blog.create(blog_parameter)
    redirect_to blogs_path
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path, notice:"削除しました"
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_parameter)
      redirect_to blogs_path, notice: "編集しました"
    else
      render 'edit'
    end
  end

  private

  def blog_parameter
    params.require(:blog).permit(:title, :content, :start_time)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
     redirect_to book_path(@book.id),notice:"You have creatad book successfully."
    else
     @user = current_user
     @books = Book.all
     render:index
    end
  end
  
  def show
   @books=Book.new
   @book = Book.find(params[:id])
   @user = @book.user
  end
  
  def edit
   @book = Book.find(params[:id])
   if @book.user == current_user
        render "edit"
    else
        redirect_to books_path
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end
  
  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      @books=Book.all
      render:edit
    end
  end
  
  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end
  
  def index
    @book = Book.new
    @books = Book.all
    @users = User.all
    @user = current_user
  end
  
  #def create
   # @books = Book.all
    #@book = Book.new(book_params)
    #@book.user_id = current_user.id
    #if @book.save
     #redirect_to book_path(@book.id)
    #else
     #render:index
    #end
  #end  
  
  
  def edit
    @user = User.find(params[:id])
    if @user == current_user
        render "edit"
    else
      redirect_to user_path(current_user)
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user),notice:"You have updated user successfully."
    else
     render:edit
    end
  end

 
  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/edit.html.erb
<p id="notice"><%= notice %></p>

<div class="toppage">
<h1 class="top">カレンダー</h1>
<br>

<div class="row">
<div class="col-md-4">
	<div class="schedule">今後の予定一覧</div>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th>タイトル</th>
      <th>日程</th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= link_to blog.title , blog %></td>
        <td><%= blog.start_time.strftime("%m-%d") %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<%= form_with(model: @blog, local: true) do |form| %>

  <div class="title">
    <div class="form-tag">タイトル</div>
    <%= form.text_field :title %>
  </div>


  <div class="content">
    <div class="form-tag">内容</div>
    <%= form.text_field :content %>
  </div>

    <div class="time">
    <div class="form-tag">時間</div>
    <%= form.datetime_select :start_time %>
  </div>

 <div class="submit">
    <%= form.submit %>
 </div>
<% end %>
</div>

<br>


<br>
<div class="col-md-8">
<%= month_calendar events: @blogs do |date, blogs| %>
  <%= date.day %>

  <% blogs.each do |blog| %>
    <div>
      <%= link_to blog.title, blog %>
    </div>
  <% end %>
<% end %>
</div>
</div>
</div>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<div class="toppage">
<h1 class="top">カレンダー</h1>
<br>

<div class="row">
<div class="col-md-4">
	<div class="schedule">今後の予定一覧</div>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th>タイトル</th>
      <th>日程</th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= link_to blog.title , blog %></td>
        <td><%= blog.start_time.strftime("%m-%d") %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<%= form_with(model: @blog, local: true) do |form| %>

  <div class="title">
    <div class="form-tag">タイトル</div>
    <%= form.text_field :title %>
  </div>


  <div class="content">
    <div class="form-tag">内容</div>
    <%= form.text_field :content %>
  </div>

    <div class="time">
    <div class="form-tag">時間</div>
    <%= form.datetime_select :start_time %>
  </div>

 <div class="submit">
    <%= form.submit %>
 </div>
<% end %>
</div>

<br>


<br>
<div class="col-md-8">
<%= month_calendar events: @blogs do |date, blogs| %>
  <%= date.day %>

  <% blogs.each do |blog| %>
    <div>
      <%= link_to blog.title, blog %>
    </div>
  <% end %>
<% end %>
</div>
</div>
</div>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>
<div class="show">
<p>
  <strong>タイトル</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>内容</strong>
  <%= @blog.content %>
</p>

<p>
  <strong>日時</strong>
  <%= @blog.start_time.strftime("%m-%d") %>
</p>

<%= link_to '編集', edit_blog_path(@blog) %>
<%= link_to '消去',blog_path(@blog.id), method: :delete, data: { confirm: '本当に?' } %>
<%= link_to '戻る', blogs_path %>
</div>

app/views/books/edit.html.erb
<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    
<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
 <% end %>


<%= form_with model: @book do |f| %>
  <div class="form-group">  
    <label for="book_title">Titele</label>
    <%= f.text_field :title,class:"form-control book_title",id:"book_title" %>
  </div>
  <div class="form-group">
    <label for="book_opinion">Opinipn</label>
    <%= f.text_area :body,class:"form-control book_body",id:"book_body" %>
  </div>
  <div class="form-group">  
  <%= f.submit "Update Book",class:"btn btn-success" %>
  </div>
    <%= link_to "Show",book_path(@book.id),class:"(@book.id)" %>
    |
    <%= link_to "Back", books_path,class:"back" %>
<% end %>

</div>
</div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
   
   <% if @book.errors.any? %>
   <h3><%= @book.errors.count %>erros prohibited this obj from being saved:</h3>
   <ul>  
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
   </ul>
  <% end %>

  <div class="row">
   
   <div class="col-md-3">  
  <h2>User info</h2>
   <%= image_tag @user.get_profile_image(100,100) %>
  <table class="table">
    <tbody>
     <tr></tr>    
     <tr>
      <th>name</th>   
      <th><%= @user.name %></th>
     </tr>
     <tr>
      <th>introduction</th> 
      <th><%= @user.introduction%></th>
     </tr>
    </tbody>
  </table>  

 <div class="row">
  <%=link_to edit_user_path(@user),class:"btn btn-outline-secondary btn-block" do %>
     <i class="fas fa-user-cog"></i>
     <% end %>
 </div>
 
<h2 class="mt-3">New book</h2>
  <%= form_with model: @book,url: '/books', method: :post do |f| %>
   <div class="form-group">
    <label for ="book_title">Titele</label>
    <%= f.text_field :title,class:"form-control book_title" %>
   </div>
   <div class="form-group">
    <label for ="book_opinion">Opinion</label>
    <%= f.text_area :body,class:"form-control book_body" %>
    </div> 
    <div class="form-group">
     <%= f.submit 'Create Book',class:"btn btn-success" %>
    </div>
  <% end %>
  
 </div>

<div class="col-md-8 offset-md-1">
<h2>Books</h2>
<table class="table table-hover table-inverse">
   <thead>
    <tr>
     <th></th>
     <th>Title</th>
     <th>Opinion</th>
     <th colspan="3"></th>
    </tr>
   </thead>
   <tbody>
   <% @books.each do |book|%>
     <tr>
      <td>
       <%= link_to user_path(book.user) do %>
        <%= image_tag book.user.get_profile_image(100,100) %>
       <% end %>
      </td>
      <td><%= link_to book.title,book_path(book.id) %></td>
      <td><%= book.body %></td>
     </tr>
     <% end %>
    </tbody>
   </table>
   </div>
   
  </div>
 </div>

app/views/books/new.html.erb
<h1>画像投稿フォーム</h1>
  <%= form_with model: @book do |f| %>
    <h4>画像</h4>
      <%= f.file_field :image, accept: "image/*" %>
    <h4>ショップ名</h4>
      <%= f.text_field :title %>
    <h4>説明</h4>
      <%= f.text_area :body %>
    <%= f.submit '投稿' %>
  <% end %>
        

app/views/books/show.html.erb
<div class="container">
  <div class="row">
   <div class="col-md-3">
    <h2>User info</h2>
     <%= image_tag @user.get_profile_image(100,100) %>
     <table class="table">
      <tbody>
       <tr></tr>
       <tr>
        <th>name</th>   
        <th><%= @user.name %></th>
       </tr>
       <tr>
        <th>introduction</th> 
        <th><%= @user.introduction%></th>
       </tr>
      </tbody>
     </table>  


 <div class="row">
  <%=link_to edit_user_path(@user),class:"btn btn-outline-secondary btn-block" do %>
     <i class="fas fa-user-cog"></i>
     <% end %>
 </div>

<h2 class="mt-3">New book</h2>
  <%= form_with model: @books,url: '/books', method: :post do |f| %>
   <div class="form-group">  
    <label for="book_title">Titele</label>
    <%= f.text_field :title,class:"form-control book_title" %>
  </div>
   <div class="form-group">
    <label for ="book_opinion">Opinion</label>
    <%= f.text_area :body,class:"form-control book_body" %>
    </div> 
    <div class="form-group">
      <%= f.submit 'Create Book',class:"btn btn-success" %>
    </div>
  <% end %>
  </div>

<div class="col-md-8 offset-md-1">
<h2>Book detail</h2>
 <table class="table">
  <tbody>
   <tr>
    <td>
     <%= link_to user_path(@user) do %> 
     <%= image_tag @user.get_profile_image(100,100) %><br>
     <%= @book.user.name %>
     <% end %>
    </td>
    <td><%= link_to @book.title %></td>
    <td><%= @book.body %></td>
  
    <% if @book.user == current_user %>
     <td><%= link_to "Edit", edit_book_path(@book.id),class:"btn btn-sm btn-success" %></td>
     <td><%= link_to "Destroy", book_path(@book.id),method: :delete,"data-confirm" => "本当に削除しますか？",class:"btn btn-sm btn-danger" %></td>
    <% end %>
    </tr>
  </tbody>
  </table>
  </div>
  
  </div>
 </div>

app/views/homes/about.html.erb
<div class="container">
 <div class="row">
  <h1 class="px-3 mx-auto">Welcome to<i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
 </div>
</div>

app/views/homes/top.html.erb
<div class="container">
 <div class="row">
  <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
   <h1>welcome to<i class="fas fa-book"></i><strong>Bookers</strong>!!</h1>
   <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
   <p>you can share and exchange your opinions , inpressions , and emotions</p>
   <p>about various books!</p>

 <div class="btn-wrapper col-10 mx-auto">
  <div class="row">
   <%= link_to "Log in", new_user_session_path,class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>
  </div>
  <div class="row">
   <%= link_to "Sign up", new_user_registration_path,class:"btn btn-success btn-sm btn-block sign_up" %>
  </div>
 </div>

  </div>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="fontawesome-i2svg-active fontawesome-i2svg-complete">
  <head>
   <title>Bookers2</title>
   <%= csrf_meta_tags %>
   <%= csp_meta_tag %>
   <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
   <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
   <script src="https://kit.fontawesome.com/1ae5e8c4d7.js" crossorigin="anonymous"></script>
   
  </head>

  <body>
   <header>
     <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
       <a class="navbar-brand" href="/">
        <span>Bookers</span>
       </a>
       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
       </button>
     
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
     <ul class="navbar-nav  ml-auto">
      <% if user_signed_in? %>
      <li>
       <%= link_to user_path(current_user.id), class:'nav-link text-light' do %>
        <i class="fas fa-home"></i>
          Home
        <% end %>
      </li>
      <li>
       <%= link_to  users_path, class:'nav-link text-light' do %>
        <i class="fas fa-users"></i>
          Users
        <% end %>
      </li>
       <li>
        <%= link_to  books_path, class:'nav-link text-light' do %>
        <i class="fas fa-book-open"></i>
          Books
        <% end %>
      </li>
      <li>
       <%= link_to  destroy_user_session_path,method: :delete, class:'nav-link text-light' do %>
        <i class="fas fa-sign-out-alt"></i>
          Log out
        <% end %>
      </li> 
     <% else %>
    <li>
       <%= link_to  root_path, class:'nav-link text-light' do %>
        <i class="fas fa-home"></i>
         Home
        <% end %>
      </li>
      <li>
       <%= link_to  home_about_path, class:'nav-link text-light' do %>
        <i class="fas fa-link"></i>
         About
        <% end %>
      </li>
      <li>
        <%= link_to  new_user_registration_path, class:'nav-link text-light' do %>
        <i class="fas fa-user-plus"></i>
         Sign up
        <% end %>
      </li>
      <li>
        <%= link_to  new_user_session_path, class:'nav-link text-light' do %>
        <i class="fas fa-sign-in-alt"></i>
         Log in
        <% end %>
      </li>
    <% end %>
    </ul>
    </div>
    </div>
   </nav>
  </header>
  
   <main>
  <%= yield %>
   </main>
  
  <footer class="border-top bg-white"style="height:50px;margin-top:500px;">
        <ul>
        <li class="list-inline-item"><img src="https://qumeru-media-preview.s3-ap-northeast-1.amazonaws.com/preview/Bootstrap/237/preview3/%E3%82%A4%E3%83%A9%E3%82%B9%E3%83%88111.png"style="height:50px"></li>
        <li class="list-inline-item"><a href="#">お問い合わせ</a></li>
        <li class="list-inline-item"><a href="#">採用情報</a></li>
        <li class="list-inline-item"><a href="#">運営会社</a></li>
        </ul>
    </footer>
  <footer>
    <div class="container">
     <div class="row">
      <div class="col-md-6">
       <p>Copy Right Infratop.inc</p>
      </div>
     </div>
    </div>
  </footer>
  
 </body>
</html>

app/views/users/edit.html.erb
<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   
<h2>User info</h2>

<%= form_with model: @user do |f| %>

 <% if @user.errors.any? %>
  <h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
   <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
   </ul>
 <% end %>
 
 <div class="form-group">
   <label for="user_name">Name</label>
   <%= f.text_field :name,class:"form-control name" ,id:"user_name"%>
 </div>
 <div class="form-group">
   <label for="user_image">Image</label>
   <%= f.file_field :profile_image,class:"form-control-file user_image", accept:"image/*" %>
  </div>
  <div class="form-group">
   <label for="user_introduction">Introduction</label><br>
   <%= f.text_area :introduction,class:"form-control introduction",id:"user_name" %>
  </div>
  <div class="form-group">
   <%= f.submit "Update User",class:"btn btn-secondary" %>
  </div>
  
<% end %>

  </div>
 </div>
</div>

app/views/users/index.html.erb
 <div class="container px-5 px-sm-0">
  
  <% if @book.errors.any? %>
   <h3><%= @book.errors.count %>erros prohibited this obj from being saved:</h3>
   <ul>  
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
   </ul>
  <% end %>

  <div class="row">
   <div class="col-md-3">
    <h2>User info</h2>
     <%= image_tag @user.get_profile_image(100,100) %>
    <table class="table">
     <tbody>
      <tr></tr>
      <tr>
       <th>name</th>   
       <th><%= @user.name %></th>
      </tr>
      <tr>
      <th>introduction</th> 
      <th><%= @user.introduction%></th>
     </tr>
     </tbody>
  </table>  

 <div class="row">
     <%=link_to edit_user_path(@user),class:"btn btn-outline-secondary btn-block" do %>
     <i class="fas fa-user-cog"></i>
     <% end %> 
 </div>

<h2 class="mt-3">New book</h2>
  <%= form_with model: @book,url: '/books', method: :post do |f| %>
   <div class="form-group">
    <label for ="book_title">Titele</label>
    <%= f.text_field :title,class:"form-control book_title" %>
   </div>
   <div class="form-group">
    <label for ="book_opinion">Opinion</label>
      <%= f.text_area :body,class:"form-control book_body" %>
    </div> 
    <div class="form-group">
     <%= f.submit 'Create Book',class:"btn btn-success" %>
    </div>
  <% end %>
  </div>
  
  <div class="col-md-8 offset-md-1">
  <h2>Users</h2>
   <table class="table">
    
    <thead>
     <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
     </tr>
    </thead>
    
    <tbody>
   <% @users.each do |user|%>
   <tr>
    <td><%= image_tag user.get_profile_image(100,100) %></td>
    <td><%= user.name %></td>
    <td><%= link_to "Show",user_path(user.id) %></td>
   </tr>
  <% end %>
  </tbody>
  </table>
 </div>
  
  </div>
 </div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
 
  <% if @book.errors.any? %>
   <h3><%= @book.errors.count %>erros prohibited this obj from being saved:</h3>
   <ul>  
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
   </ul>
  <% end %>
  
  <div class="row">
   <div class="col-md-3">
    
    <h2>User info</h2>
     <%= image_tag @user.get_profile_image(100,100) %>
    <table class="table">
    <tbody>
     <tr></tr>
     <tr>
      <th>name</th>   
      <th><%= @user.name %></th>
     </tr>
     <tr>
      <th>introduction</th> 
      <th><%= @user.introduction%></th>
     </tr>
    </tbody>
   </table> 
   
   <div class="row">   
     <%=link_to edit_user_path(@user),class:"btn btn-outline-secondary btn-block" do %>
     <i class="fas fa-user-cog"></i>
     <% end %>
   </div>
   
 <h2 class="mt-3">New book</h2>
  <%= form_with model: @book,url: '/books', method: :post do |f| %>
   <div class="form-group">  
    <label for="book_title">Titele</label>
    <%= f.text_field :title,class:"form-control book_title" %>
   </div>
   <div class="form-group">
    <label for ="book_opinion">Opinion</label>
    <%= f.text_area :body,class:"form-control book_body" %>
    </div> 
    
    <div class="form-group">
     <%= f.submit 'Create Book',class:"btn btn-success" %>
    </div>
  <% end %>
 </div>

<div class="col-md-8 offset-md-1">
 <h2>Books</h2>
 <table class="table table-hover table-inverse">
  <thead>
   <tr>
     <th></th>
     <th>Title</th>
     <th>Opinion</th>
     <th colspan="3"></th>
    </tr>
  </thead>
  
  <% @books.each do |book|%>
  <tbody>
   <tr>
    <td>
     <%= link_to user_path(@user) do %>
     <%= image_tag @user.get_profile_image(100,100) %>
     <% end %>
     </td>
    <td><%= link_to book.title,book_path(book.id) %></td>
    <td><%= book.body %></td>
   </tr>
  </tbody>
  <% end %>
  </table>
 </div>
 
 </div>
</div>



 